# Generated by Django 4.2.4 on 2023-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyfact',
            name='fact_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yearlyplan',
            name='plan_value',
            field=models.IntegerField(null=True),
        ),
    ]
